language: python

jobs:
  include:
    - python: 3.8
      name: "Build and deploy documentation"
      if: type != pull_request AND branch = master
      install:
        - sudo apt-get install graphviz
        - pip install -r requirements.txt
        - pip install -r docs/requirements.txt
      script:
        - python setup.py build_ext --inplace
      after_success:
        - mkdir html
        - touch html/.nojekyll
        - git fetch --all
        - python -I -m sphinx_multiversion docs html
        - cp docs/assets/index.html html/index.html
      deploy:
        - provider: pages
          skip_cleanup: true
          keep_history: false
          token: $GITHUB_TOKEN
          local_dir: html
          on:
            branch: master
            repo: isaksamsten/wildboar

    - python: 3.8
      name: "Build, test and deploy source distribution"
      before_install:
        - python --version
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-dev.txt
      script:
        - python setup.py sdist
        - pip install .
        - python -m pytest --pyargs wildboar
      after_success:
        - |
          if [[ $TRAVIS_TAG ]]; then
                pip install twine
                python -m twine upload dist/*.tar.gz
          fi
    - services: docker
      name: "Build and deploy GNU/Linux binaries"
      if: type != pull_request AND tag IS present
      install:
        - python3 -m pip install cibuildwheel==1.1.0
      script:
        - python3 -m cibuildwheel --output-dir wheelhouse
      after_success:
        - |
          if [[ $TRAVIS_TAG ]]; then
                python3 -m pip install twine
                python3 -m twine upload wheelhouse/*.whl
          fi
    - os: osx
      language: shell
      name: "Build and deploy MacOS binaries"
      if: type != pull_request AND tag IS present
      install:
        - python3 -m pip install cibuildwheel==1.6.4
      script:
        - python3 -m cibuildwheel --output-dir wheelhouse
      after_success:
        - |
          if [[ $TRAVIS_TAG ]]; then
                python3 -m pip install twine
                python3 -m twine upload wheelhouse/*.whl
          fi
    - os: windows
      language: shell
      name: "Build and deploy Windows binaries"
      if: type != pull_request AND tag IS present
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - ln -s /c/Python38/python.exe /c/Python38/python3.exe
      install:
        - python3 -m pip install cibuildwheel==1.6.4
      script:
        - python3 -m cibuildwheel --output-dir wheelhouse
      after_success:
        - |
          if [[ $TRAVIS_TAG ]]; then
                python3 -m pip install twine
                python3 -m twine upload wheelhouse/*.whl
          fi
env:
  global:
    - TWINE_USERNAME=__token__
    - CIBW_BUILD=cp36-* cp37-* cp38-*
    - CIBW_SKIP="*-win32 *-manylinux_i686"